export default ({ theme }) => [{
    type: 'inside',
    xAxisIndex: null,
    yAxisIndex: null,
    angleAxisIndex: null,
    radiusAxisIndex: null,
    filterMode: 'filter',
    start: 0,
    end: 100,
    startValue: null,
    endValue: null,
    orient: null,
    throttle: 100,
}, {
    type: 'slider',
    show: true,
    backgroundColor: 'rgba(47,69,84,0)',
    dataBackgroundColor: '#ddd',
    fillerColor: theme.fill,
    handleColor: theme.line,
    handleSize: 10,
    labelPrecision: 'auto',
    labelFormatter: null,
    showDetail: false,
    realtime: true,
    zoomLock: false,
    // textStyle: {...},
    xAxisIndex: null,
    yAxisIndex: null,
    angleAxisIndex: null,
    radiusAxisIndex: null,
    filterMode: 'filter',
    start: 0,
    end: 100,
    startValue: null,
    endValue: null,
    orient: null,
    throttle: 100,
    zlevel: 0,
    z: 2,
    top: 95,
    height: 20,
}];

    // start: 20,
    // end: 50,
    // height: 20,
    // backgroundColor: theme.background,
    // dataBackgroundColor: theme.text,
    // fillerColor:
    // handleColor:
    // handleSize: 10,
    // showDetail: false,
