export default ({
    CALL: 'You win the payout if the exit spot is strictly higher than the entry spot.',
    PUT: 'You win the payout if the exit spot is strictly lower than the entry spot.',
    CALL2: 'You win the payout if the exit spot is strictly higher than the barrier.',
    PUT2: 'You win the payout if the exit spot is strictly lower than the barrier.',
    ONETOUCH: 'You win the payout if the market touches the barrier at any time during the contract period.',
    NOTOUCH: 'You win the payout if the market never touches the barrier at any time during the contract period.',
    EXPIRYRANGE: 'You win the payout if the exit spot is strictly higher than the Low barrier AND strictly lower than the High barrier.',
    EXPIRYMISS: 'You win the payout if the exit spot is EITHER strictly higher than the High barrier, OR strictly lower than the Low barrier.',
    RANGE: 'You win the payout if the market stays between (does not touch) either the High barrier or the Low barrier at any time during the contract period.',
    UPORDOWN: 'You win the payout if the market touches either the High barrier or the Low barrier at any time during the contract period.',
    ASIANU: 'You will win the payout if the last tick is higher than the average of the ticks.',
    ASIAND: 'You will win the payout if the last tick is lower than the average of the ticks.',
    DIGITMATCH: 'You will win the payout if the last digit of the last tick is the same as your prediction.',
    DIGITDIFF: 'You will win the payout if the last digit of the last tick is not the same as your prediction.',
    DIGITEVEN: 'You will win the payout if the last digit of the last tick is an even number (i.e., 2, 4, 6, 8, or 0).',
    DIGITODD: 'You will win the payout if the last digit of the last tick is an odd number (i.e., 1, 3, 5, 7, or 9).',
    DIGITOVER: 'You will win the payout if the last digit of the last tick is greater than your prediction.',
    DIGITUNDER: 'You will win the payout if the last digit of the last tick is less than your prediction.',
    SPREADU: 'Spread contracts payout based on the movement of the index relative to the entry level of the contract.',
    SPREADD: 'Spread contracts payout based on the movement of the index relative to the entry level of the contract.',
});
