export const assetsFromServer = [
    {
        "market": "indices",
        "symbol": "FCHI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "French Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxAUDJPY",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "AUD/JPY",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "stocks",
        "symbol": "FPEDF",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Electricite de France",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPDG",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Vinci",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxUSDJPY",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "USD/JPY",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "stocks",
        "symbol": "FPCA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Carrefour",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxAUDCAD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "AUD/CAD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "random",
        "symbol": "R_75",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_index",
        "display_name": "Random 75 Index",
        "submarket_display_name": "Indices",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "indices",
        "symbol": "TOP40",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "South African Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "NAASML",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "amsterdam",
        "display_name": "ASML Holding",
        "submarket_display_name": "Dutch Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPFP",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "TOTAL",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "WLDUSD",
        "market_display_name": "Forex",
        "symbol_type": "smart_fx",
        "exchange_is_open": 1,
        "submarket": "smart_fx",
        "display_name": "USD Index",
        "submarket_display_name": "Smart FX",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "stocks",
        "symbol": "FPCS",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "AXA",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxAUDPLN",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "AUD/PLN",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "indices",
        "symbol": "GDAXI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "German Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPBN",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Danone",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "BBABI",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "belgium",
        "display_name": "AB Inbev",
        "submarket_display_name": "Belgian Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPKER",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Kering",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "BBUCB",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "belgium",
        "display_name": "UCB",
        "submarket_display_name": "Belgian Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "STI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "asia_oceania",
        "display_name": "Singapore Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "RDBEAR",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_daily",
        "display_name": "Random Bear",
        "submarket_display_name": "Quotidians",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxAUDNZD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "AUD/NZD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxEURNZD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "EUR/NZD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "BBGBLB",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "belgium",
        "display_name": "Groupe Bruxelles Lambert",
        "submarket_display_name": "Belgian Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxUSDCAD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "USD/CAD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "stocks",
        "symbol": "FPSAF",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Safran",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "OBX",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "Norwegian Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "NARDSA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "amsterdam",
        "display_name": "Royal Dutch Shell",
        "submarket_display_name": "Dutch Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "JCI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "asia_oceania",
        "display_name": "Jakarta Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "forex",
        "symbol": "frxEURAUD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/AUD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "stocks",
        "symbol": "NAUNA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "amsterdam",
        "display_name": "Unilever",
        "submarket_display_name": "Dutch Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxGBPJPY",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "GBP/JPY",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "forex",
        "symbol": "frxEURCHF",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/CHF",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "forex",
        "symbol": "frxEURJPY",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/JPY",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "random",
        "symbol": "RDVENUS",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_nightly",
        "display_name": "Random Venus",
        "submarket_display_name": "Nocturnes",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "NAHEIA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "amsterdam",
        "display_name": "Heineken",
        "submarket_display_name": "Dutch Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPVIV",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Vivendi",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "BBKBC",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "belgium",
        "display_name": "KBC Groep",
        "submarket_display_name": "Belgian Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPSU",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Schneider Electric",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxGBPUSD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "GBP/USD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "WLDGBP",
        "market_display_name": "Forex",
        "symbol_type": "smart_fx",
        "exchange_is_open": 1,
        "submarket": "smart_fx",
        "display_name": "GBP Index",
        "submarket_display_name": "Smart FX",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "stocks",
        "symbol": "FPRI",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Pernod Ricard",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPAI",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Air Liquide",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "DJI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "americas",
        "display_name": "Wall Street Index",
        "submarket_display_name": "Americas",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxGBPNZD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "GBP/NZD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "FPEI",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Essilor International",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPOR",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "L'Oreal",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPACA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Credit Agricole",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxAUDCHF",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "AUD/CHF",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "BBBELG",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "belgium",
        "display_name": "Belgacom",
        "submarket_display_name": "Belgian Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxUSDPLN",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "USD/PLN",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxUSDCHF",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "USD/CHF",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "forex",
        "symbol": "frxNZDJPY",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "NZD/JPY",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "forex",
        "symbol": "frxGBPCAD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "GBP/CAD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "commodities",
        "symbol": "frxBROUSD",
        "market_display_name": "Commodities",
        "symbol_type": "commodities",
        "exchange_is_open": 0,
        "submarket": "energy",
        "display_name": "Oil/USD",
        "submarket_display_name": "Energy",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPGSZ",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "GDF Suez",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "SPC",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "americas",
        "display_name": "US Index",
        "submarket_display_name": "Americas",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "WLDEUR",
        "market_display_name": "Forex",
        "symbol_type": "smart_fx",
        "exchange_is_open": 1,
        "submarket": "smart_fx",
        "display_name": "EUR Index",
        "submarket_display_name": "Smart FX",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "stocks",
        "symbol": "FPMC",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Moet Hennessy Louis Vuitton",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPORA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Orange",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "N225",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "asia_oceania",
        "display_name": "Japanese Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "RDBULL",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_daily",
        "display_name": "Random Bull",
        "submarket_display_name": "Quotidians",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "indices",
        "symbol": "DFMGI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "middle_east",
        "display_name": "Dubai Index",
        "submarket_display_name": "Middle East",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPRNO",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Renault",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "R_25",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_index",
        "display_name": "Random 25 Index",
        "submarket_display_name": "Indices",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "forex",
        "symbol": "frxUSDNOK",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "USD/NOK",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "random",
        "symbol": "RDMARS",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_nightly",
        "display_name": "Random Mars",
        "submarket_display_name": "Nocturnes",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxEURCAD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/CAD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "stocks",
        "symbol": "FPGLE",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Societe Generale",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "SSMI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "Swiss Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxGBPNOK",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "GBP/NOK",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "NAINGA",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "amsterdam",
        "display_name": "ING",
        "submarket_display_name": "Dutch Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "R_100",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_index",
        "display_name": "Random 100 Index",
        "submarket_display_name": "Indices",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPAIR",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Airbus Group",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "stocks",
        "symbol": "FPBNP",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "BNP Paribas",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "BFX",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "Belgian Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxGBPPLN",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "GBP/PLN",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxGBPAUD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "GBP/AUD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "forex",
        "symbol": "frxUSDSEK",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "USD/SEK",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "indices",
        "symbol": "ISEQ",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "Irish Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "HSI",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "asia_oceania",
        "display_name": "Hong Kong Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxUSDMXN",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "USD/MXN",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxAUDUSD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "AUD/USD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "forex",
        "symbol": "frxGBPCHF",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "GBP/CHF",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "stocks",
        "symbol": "FPSAN",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "SANOFI",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "indices",
        "symbol": "AS51",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "asia_oceania",
        "display_name": "Australian Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxEURUSD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/USD",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "random",
        "symbol": "RDYIN",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_nightly",
        "display_name": "Random Yin",
        "submarket_display_name": "Nocturnes",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "stocks",
        "symbol": "FPSGO",
        "market_display_name": "Stocks",
        "symbol_type": "individualstock",
        "exchange_is_open": 0,
        "submarket": "france",
        "display_name": "Cie de Saint-Gobain",
        "submarket_display_name": "French Stocks",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "forex",
        "symbol": "frxEURGBP",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "major_pairs",
        "display_name": "EUR/GBP",
        "submarket_display_name": "Major Pairs",
        "is_trading_suspended": 0,
        "pip": "0.00001"
    },
    {
        "market": "indices",
        "symbol": "BSESENSEX30",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "asia_oceania",
        "display_name": "Bombay Index",
        "submarket_display_name": "Asia/Oceania",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "RDMOON",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_daily",
        "display_name": "Random Moon",
        "submarket_display_name": "Quotidians",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "WLDAUD",
        "market_display_name": "Forex",
        "symbol_type": "smart_fx",
        "exchange_is_open": 1,
        "submarket": "smart_fx",
        "display_name": "AUD Index",
        "submarket_display_name": "Smart FX",
        "is_trading_suspended": 0,
        "pip": "0.001"
    },
    {
        "market": "random",
        "symbol": "RDYANG",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_nightly",
        "display_name": "Random Yang",
        "submarket_display_name": "Nocturnes",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "random",
        "symbol": "R_50",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_index",
        "display_name": "Random 50 Index",
        "submarket_display_name": "Indices",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "forex",
        "symbol": "frxNZDUSD",
        "market_display_name": "Forex",
        "symbol_type": "forex",
        "exchange_is_open": 1,
        "submarket": "minor_pairs",
        "display_name": "NZD/USD",
        "submarket_display_name": "Minor Pairs",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    },
    {
        "market": "indices",
        "symbol": "AEX",
        "market_display_name": "Indices",
        "symbol_type": "stockindex",
        "exchange_is_open": 0,
        "submarket": "europe_africa",
        "display_name": "Dutch Index",
        "submarket_display_name": "Europe/Africa",
        "is_trading_suspended": 0,
        "pip": "0.01"
    },
    {
        "market": "random",
        "symbol": "RDSUN",
        "market_display_name": "Randoms",
        "symbol_type": "stockindex",
        "exchange_is_open": 1,
        "submarket": "random_daily",
        "display_name": "Random Sun",
        "submarket_display_name": "Quotidians",
        "is_trading_suspended": 0,
        "pip": "0.0001"
    }
];
