export default [
    {
        "contract_display": "ends outside",
        "market": "indices",
        "high_barrier": "10123.24",
        "max_contract_duration": "365d",
        "barrier_category": "euro_non_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "low_barrier": "9626.00",
        "contract_category_display": "Ends In/Out",
        "contract_type": "EXPIRYMISS",
        "min_contract_duration": "7d",
        "sentiment": "high_vol",
        "barriers": 2,
        "contract_category": "endsinout",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "ends between",
        "market": "indices",
        "high_barrier": "10123.24",
        "max_contract_duration": "365d",
        "barrier_category": "euro_non_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "low_barrier": "9626.00",
        "contract_category_display": "Ends In/Out",
        "contract_type": "EXPIRYRANGE",
        "min_contract_duration": "7d",
        "sentiment": "low_vol",
        "barriers": 2,
        "contract_category": "endsinout",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "touches",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier": "10123.24",
        "barrier_category": "american",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Touch/No Touch",
        "contract_type": "ONETOUCH",
        "min_contract_duration": "7d",
        "sentiment": "high_vol",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "does not touch",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier": "10123.24",
        "barrier_category": "american",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Touch/No Touch",
        "contract_type": "NOTOUCH",
        "min_contract_duration": "7d",
        "sentiment": "low_vol",
        "barriers": 1,
        "contract_category": "touchnotouch",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "stays between",
        "market": "indices",
        "high_barrier": "10123.24",
        "max_contract_duration": "365d",
        "barrier_category": "american",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "low_barrier": "9626.00",
        "contract_category_display": "Stays In/Goes Out",
        "contract_type": "RANGE",
        "min_contract_duration": "7d",
        "sentiment": "low_vol",
        "barriers": 2,
        "contract_category": "staysinout",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "goes outside",
        "market": "indices",
        "high_barrier": "10123.24",
        "max_contract_duration": "365d",
        "barrier_category": "american",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "low_barrier": "9626.00",
        "contract_category_display": "Stays In/Goes Out",
        "contract_type": "UPORDOWN",
        "min_contract_duration": "7d",
        "sentiment": "high_vol",
        "barriers": 2,
        "contract_category": "staysinout",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "higher",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "CALL",
        "min_contract_duration": "1d",
        "sentiment": "up",
        "barriers": 0,
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "daily",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica"
    },
    {
        "contract_display": "lower",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "PUT",
        "min_contract_duration": "1d",
        "sentiment": "down",
        "barriers": 0,
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "daily",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica"
    },
    {
        "contract_display": "higher",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier": "10123.24",
        "barrier_category": "euro_non_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "CALL",
        "min_contract_duration": "7d",
        "sentiment": "up",
        "barriers": 1,
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "lower",
        "market": "indices",
        "max_contract_duration": "365d",
        "barrier": "10123.24",
        "barrier_category": "euro_non_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "PUT",
        "min_contract_duration": "7d",
        "sentiment": "down",
        "barriers": 1,
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "daily",
        "landing_company": "costarica",
        "underlying_symbol": "GDAXI"
    },
    {
        "contract_display": "higher",
        "market": "indices",
        "max_contract_duration": "1d",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "CALL",
        "min_contract_duration": "5m",
        "barriers": 0,
        "sentiment": "up",
        "contract_category": "callput",
        "start_type": "forward",
        "expiry_type": "intraday",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica",
        "forward_starting_options": [
            {
                "open": 1459234800,
                "close": 1459265400,
                "date": 1459209600
            },
            {
                "open": 1459321200,
                "close": 1459351800,
                "date": 1459296000
            },
            {
                "open": 1459407600,
                "close": 1459438200,
                "date": 1459382400
            }
        ]
    },
    {
        "contract_display": "lower",
        "market": "indices",
        "max_contract_duration": "1d",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "contract_category_display": "Up/Down",
        "contract_type": "PUT",
        "min_contract_duration": "5m",
        "barriers": 0,
        "sentiment": "down",
        "contract_category": "callput",
        "start_type": "forward",
        "expiry_type": "intraday",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica",
        "forward_starting_options": [
            {
                "open": 1459234800,
                "close": 1459265400,
                "date": 1459209600
            },
            {
                "open": 1459321200,
                "close": 1459351800,
                "date": 1459296000
            },
            {
                "open": 1459407600,
                "close": 1459438200,
                "date": 1459382400
            }
        ]
    },
    {
        "contract_display": "higher",
        "market": "indices",
        "max_contract_duration": "1h",
        "payout_limit": "5000",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "max_historical_pricer_duration": "1h",
        "contract_category_display": "Up/Down",
        "contract_type": "CALL",
        "min_contract_duration": "15m",
        "barriers": 0,
        "sentiment": "up",
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "intraday",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica",
        "min_historical_pricer_duration": "15m"
    },
    {
        "contract_display": "lower",
        "market": "indices",
        "max_contract_duration": "1h",
        "payout_limit": "5000",
        "barrier_category": "euro_atm",
        "exchange_name": "FSE",
        "submarket": "europe_africa",
        "max_historical_pricer_duration": "1h",
        "contract_category_display": "Up/Down",
        "contract_type": "PUT",
        "min_contract_duration": "15m",
        "barriers": 0,
        "sentiment": "down",
        "contract_category": "callput",
        "start_type": "spot",
        "expiry_type": "intraday",
        "underlying_symbol": "GDAXI",
        "landing_company": "costarica",
        "min_historical_pricer_duration": "15m"
    }
];
