export const SERVER_DATA_PORTFOLIO = 'SERVER_DATA_PORTFOLIO';
export const SERVER_DATA_PROPOSAL_OPEN_CONTRACT = 'SERVER_DATA_PROPOSAL_OPEN_CONTRACT';
export const DETAILS_FOR_CONTRACT = 'DETAILS_FOR_CONTRACT';

export const SERVER_DATA_AUTHORIZE = 'SERVER_DATA_AUTHORIZE';
export const SERVER_DATA_BALANCE = 'SERVER_DATA_BALANCE';
export const SERVER_DATA_ASSETS = 'SERVER_DATA_ASSETS';
export const SERVER_DATA_OFFERINGS = 'SERVER_DATA_OFFERINGS';
export const SERVER_DATA_ACTIVE_SYMBOLS = 'SERVER_DATA_ACTIVE_SYMBOLS';
export const SERVER_DATA_TRADING_TIMES = 'SERVER_DATA_TRADING_TIMES';
export const SERVER_DATA_STATEMENT = 'SERVER_DATA_STATEMENT';

export const SERVER_DATA_TICK_STREAM = 'SERVER_DATA_TICK_STREAM';
export const SERVER_DATA_TICK_HISTORY = 'SERVER_DATA_TICK_HISTORY';

export const SERVER_DATA_PROFIT_TABLE = 'SERVER_DATA_PROFIT_TABLE';

export const FILTER_ASSETS = 'FILTER_ASSETS';

export const UPDATE_TICK_TRADE_PARAMETERS = 'UPDATE_TICK_TRADE_PARAMETERS';
export const SERVER_DATA_PAYOUT_CURRENCIES = 'SERVER_DATA_PAYOUT_CURRENCIES';

export const WORKSPACE_VIEW_ASSET_DETAILS = 'WORKSPACE_VIEW_ASSET_DETAILS';
export const WORKSPACE_ASSET_SELECT = 'WORKSPACE_ASSET_SELECT';
export const WORKSPACE_FAVOR_ASSET = 'WORKSPACE_FAVOR_ASSET';
export const WORKSPACE_UNFAVOR_ASSET = 'WORKSPACE_UNFAVOR_ASSET';
