export default {
    '': {
        'project-id-version': 'I 18N',
        'report-msgid-bugs-to': '',
        'pot-creation-date': '',
        'po-revision-date': '2016-08-05 03:59+0000',
        'last-translator': 'Putri Kumala <putri@regentmarkets.com>',
        'language-team': 'Indonesian <https://hosted.weblate.org/projects/binary-app/next-gen-app/id/>',
        language: 'id',
        'mime-version': '1.0',
        'content-type': 'text/plain; charset=UTF-8',
        'content-transfer-encoding': '8bit',
        'plural-forms': 'nplurals=1; plural=0;',
        'x-generator': 'Weblate 2.8-dev',
    },
    All: [null, 'Semua'],
    Property: [null, 'Milik'],
    Value: [null, 'Nilai'],
    Balance: [null, 'Saldo'],
    Trade: [null, 'Trade'],
    Watchlist: [null, 'Daftar pantauan'],
    'Open Positions': [null, 'Kontrak Berjalan'],
    'Profit Table': [null, 'Tabel Laba Rugi'],
    Statement: [null, 'Pernyataan'],
    Settings: [null, 'Pengaturan'],
    'Sign Out': [null, 'Keluar'],
    View: [null, 'Lihat'],
    'Ref.': [null, 'Ref.'],
    Purchase: [null, 'Beli'],
    Indicative: [null, 'Indikatif'],
    'Purchase Date': [null, 'Tanggal Beli'],
    'Purchase Price': [null, 'Harga Beli'],
    'Sale Date': [null, 'Tanggal Jual'],
    'Sale Price': [null, 'Harga Jual'],
    'Profit/Loss': [null, 'Untung/Rugi'],
    Total: [null, 'Total'],
    Location: [null, 'Lokasi'],
    Update: [null, 'Memperbarui'],
    Details: [null, 'Rincian'],
    'Trading Limits': [null, 'Batasan Trading'],
    Item: [null, 'Bagian'],
    'Limit ({currency})': [null, 'Batas ({currency})'],
    'Maximum number of open positions': [
        null,
        'Maksimal jumlah posisi terbuka',
    ],
    'Maximum account cash balance': [null, 'Maksimum saldo tunai'],
    'Maximum daily turnover': [null, 'Maksimum turnover harian'],
    'Maximum aggregate payouts on open positions': [
        null,
        'Jumlah maksimal hasil rata-rata pada posisi terbuka',
    ],
    'Withdrawal limits': [null, 'Batas penarikan'],
    'Your withdrawal limit is {limit} (or equivalent in other currency).': [
        null,
        'Batas penarikan Anda adalah {limit} (atau setara dengan mata uang lain).',
    ],
    'You have already withdrawn the equivalent of EUR {drawn}.': [
        null,
        'Anda telah menarik dana setara dengan EUR {drawn}.',
    ],
    'An additional password can be used to restrict access to the cashier.': [
        null,
        'Kata sandi tambahan dapat digunakan untuk membatasi akses ke kasir.',
    ],
    'Sign In': [null, 'Masuk'],
    'Get your API token': [null, 'Dapatkan token API Anda'],
    'Create Account': [null, 'Daftar Akun'],
    Action: [null, 'Aksi'],
    'Credit/Debit': [null, 'Kredit/Debit'],
    'Purchase Time': [null, 'Waktu Beli'],
    Back: [null, 'Kembali'],
    'Place Order': [null, 'Beli Kontrak'],
    '{asset} will {type} over next {duration}': [
        null,
        '{asset} akan {type} pada {duration} berikutnya',
    ],
    Price: [null, 'Harga'],
    Asset: [null, 'Aset'],
    Type: [null, 'Tipe'],
    Ticks: [null, 'Hasil Tik'],
    Amount: [null, 'Jumlah'],
    'Trade Confirmation': [null, 'Konfirmasi Trading'],
    'Entry spot': [null, 'Spot awal'],
    'Exit spot': [null, 'Spot akhir'],
    Next: [null, 'Lanjutkan'],
    'Open Account': [null, 'Daftar Akun'],
    'Upgrade to Real Money Account': [null, 'Tingkatkan ke Akun Uang Riil'],
    'Date of birth': [null, 'Tanggal lahir'],
    'Home Address': [null, 'Alamat Rumah'],
    Security: [null, 'Keamanan'],
    Spot: [null, 'Posisi'],
    Change: [null, 'Perubahan'],
    Chart: [null, 'Grafik'],
    'Purchase For': [null, 'Untuk Pembelian'],
    Rise: [null, 'Rise'],
    Stake: [null, 'Modal'],
    Payout: [null, 'Hasil'],
    Deposit: [null, 'Deposit'],
    Transactions: [null, 'Transaksi'],
    Opens: [null, 'Buka'],
    Closes: [null, 'Tutup'],
    Personal: [null, 'Pribadi'],
    General: [null, 'Umum'],
    'Trading Times': [null, 'Waktu Trading'],
    'Asset Index': [null, 'Indeks Aset'],
    Today: [null, 'Hari ini'],
    Yesterday: [null, 'Kemarin'],
    Tomorrow: [null, 'Besok'],
    Takeout: [null, 'Mengambil'],
    News: [null, 'Berita'],
    Resources: [null, 'Sumber'],
    'Last 7 Days': [null, '7 Hari Terakhir'],
    'Last 30 Days': [null, '30 Hari Terakhir'],
    'Daily Report': [null, 'Laporan Harian'],
    'Up/Down': [null, 'Up/Down'],
    'Touch/No Touch': [null, 'Touch/No Touch'],
    'Ends In/Out': [null, 'Ends In/Out'],
    'Stays In/Goes Out': [null, 'Stays In/Goes Out'],
    Settles: [null, 'Diselesaikan'],
    Language: [null, 'Bahasa'],
    'Color Theme': [null, 'Warna Tema'],
    Light: [null, 'Terang'],
    Dark: [null, 'Gelap'],
    Name: [null, 'Nama'],
    'Date Of Birth': [null, 'Tanggal Lahir'],
    'Country Of Residence': [null, 'Negara Domisili'],
    Email: [null, 'Email'],
    'There are no transactions for selected period': [
        null,
        'Tidak ditemukan transaksi bagi periode yang dipilih',
    ],
    Sell: [null, 'Jual'],
    Buy: [null, 'Beli'],
    'Digit Even': [null, 'Digit Even'],
    Touches: [null, 'Touches'],
    'Digit Over': [null, 'Digit Over'],
    'Digit Match': [null, 'Digit Match'],
    'Digit Under': [null, 'Digit Under'],
    'Digit Odd': [null, 'Digit Odd'],
    'Digit Differs': [null, 'Digit Differs'],
    'No Touch': [null, 'No Touch'],
    Fall: [null, 'Fall'],
    'Asian Down': [null, 'Asian Down'],
    'Asian Up': [null, 'Asian Up'],
    'Search For Assets': [null, 'Pencarian Aset'],
    'Start times': [null, 'Waktu mulai'],
    Durations: [null, 'Durasi'],
    'Payout/Stake': [null, 'Hasil/Modal'],
    'Purchase for': [null, 'Pembelian untuk'],
    payout: [null, 'hasil'],
    stake: [null, 'modal'],
    'Self Exclusion': [null, 'Pengecualian Diri'],
    'Cashier Lock': [null, 'Penguncian Kasir'],
    'Change Password': [null, 'Mengganti Kata sandi'],
    Password: [null, 'Kata sandi'],
    'Tick Trade': [null, 'Trading Tik'],
    'Full Trade': [null, 'Trading Penuh'],
    Address: [null, 'Alamat'],
    'Town/City': [null, 'Kota'],
    'State/Province': [null, 'Daerah/Provinsi'],
    Telephone: [null, 'Telepon'],
    'Postal Code / ZIP': [null, 'Kode Pos'],
    'Cashier password': [null, 'Kata sandi kasir'],
    'Re-enter your password': [null, 'Isi ulang kata sandi'],
    'Current password': [null, 'Kata sandi saat ini'],
    'New password': [null, 'Kata sandi baru'],
    'Verify new password': [null, 'Memeriksa kata sandi baru'],
    'Daily turnover limit': [null, 'Batas beli harian'],
    'Once this limit is reached, you may no longer deposit.': [
        null,
        'Setelah batas ini tercapai, Anda tidak dapat mendeposit.',
    ],
    'Maximum aggregate contract purchases per day.': [
        null,
        'Maksimum total pembelian kontrak per hari.',
    ],
    'Daily limit on losses': [null, 'Batas rugi harian'],
    'Maximum aggregate loss per day.': [null, 'Maksimum total rugi per hari.'],
    '7-day turnover limit': [null, 'batas beli 7 hari'],
    'Maximum aggregate contract purchases over a 7-day period.': [
        null,
        'Maksimum total beli kontrak dalam periode 7 hari.',
    ],
    '7-day limit on losses': [null, 'batas rugi 7 hari'],
    'Maximum aggregate loss over a 7-day period.': [
        null,
        'Maksimum total rugi dalam periode 7 hari.',
    ],
    '30-day turnover limit': [null, 'batas beli 30 hari'],
    'Maximum aggregate contract purchases over a 30-day period.': [
        null,
        'Maksimum total beli kontrak selama periode 30 hari.',
    ],
    '30-day limit on losses': [null, 'Batas rugi 30 hari'],
    'Maximum aggregate loss over a 30-day period.': [
        null,
        'Maksimum total rugi selama periode 30 hari.',
    ],
    'Session duration limit, in minutes': [
        null,
        'Batas sesi durasi, dalam menit',
    ],
    'You will be automatically logged out after such time.': [
        null,
        'Anda akan secara otomatis keluar setelah waktu tersebut.',
    ],
    'Exclude me from the website until': [
        null,
        'Kecualikan saya dari website hingga',
    ],
    Limits: [null, 'Batasan'],
    'Please enter date in the format YYYY-MM-DD.': [
        null,
        'Silahkan masukkan tanggal dalam format YYYY-MM-DD.',
    ],
    'New Trade': [null, 'Trading Baru'],
    'Trade Type': [null, 'Jenis Trading'],
    'Random 100 Index': [null, 'Random 100 Index'],
    Article: [null, 'Artikel'],
    'Start Later': [null, 'Mulai Nanti'],
    'Buy Price': [null, 'Harga Beli'],
    'Earning (%)': [null, 'Pendapatan (%)'],
    Profit: [null, 'Untung'],
    'Entry Price': [null, 'Harga Awal'],
    'Exit Price': [null, 'Harga Akhir'],
    'Indicative Price': [null, 'Harga Indikatif'],
    'Potential Profit': [null, 'Potensi Untung'],
    'Sell at Market': [null, 'Jual pada Pasar'],
    'Go back': [null, 'Kembali'],
    'You lost ': [null, 'Anda rugi '],
    Close: [null, 'Tutup'],
    Low: [null, 'Rendah'],
    High: [null, 'Tinggi'],
    Open: [null, 'Buka'],
    Date: [null, 'Tanggal'],
    'Upcoming Events': [null, 'Acara Mendatang'],
    Win: [null, 'Untung'],
    Loss: [null, 'Rugi'],
    'Full Screen': [null, 'Layar Penuh'],
    'Start Now': [null, 'Mulai Sekarang'],
    'Daily Prices': [null, 'Harga Harian'],
    Spreads: [null, 'Spreads'],
    'Confirm new password': [null, 'Konfirmasi kata sandi baru'],
    TICK: [null, 'TIK'],
    Minutes: [null, 'Menit'],
    Seconds: [null, 'Detik'],
    Hours: [null, 'Jam'],
    Days: [null, 'Hari'],
    'N/A': [null, 'N/A'],
    Duration: [null, 'Durasi'],
    'Start Time': [null, 'Waktu Mulai'],
    Now: [null, 'Sekarang'],
    Later: [null, 'Kemudian'],
    return: [null, 'laba'],
    Portfolio: [null, 'Portopolio'],
    Video: [null, 'Video'],
    'Digit Stats': [null, 'Digit Stats'],
    Favorites: [null, 'Favorit'],
    'Open For Trading': [null, 'Tersedia Untuk Trading'],
    Closed: [null, 'Tutup'],
    'Contract ID': [null, 'ID Kontrak'],
    'Reference ID': [null, 'ID Referensi'],
    'Entry Spot': [null, 'Spot Awal'],
    'Entry Spot Time': [null, 'Waktu Spot Awal'],
    'Potential Payout': [null, 'Potensi Hasil'],
    'Exit Spot': [null, 'Spot Akhir'],
    'Exit Spot Time': [null, 'Waktu Spot Akhir'],
    'Sell Price': [null, 'Harga Jual'],
    'Sell Time': [null, 'Waktu Jual'],
    'Trade Again': [null, 'Trading Lagi'],
    Barrier: [null, 'Batasan'],
    'You Won': [null, 'Anda Untung'],
    'You Lost': [null, 'Anda Rugi'],
    'To change your name, date of birth, country of residence, or email, contact Customer Support.': [
        null,
        'Untuk merubah nama, tanggal lahir, negara domisili atau email, hubungi Customer Support.',
    ],
    'Cashier is locked per your request. To unlock it, enter your password.': [
        null,
        'Bagian kasir telah dikunci sesuai dengan permintaan Anda. Untuk membuka, masukkan kata sandi.',
    ],
    'Unlock Cashier': [null, 'Membuka Kasir'],
    'Time out until': [null, 'Berhenti hingga'],
    'No transactions for the selected period': [
        null,
        'Tidak ditemukan transaksi pada periode yang dipilih',
    ],
    'You have no open contracts': [
        null,
        'Anda tidak memiliki kontrak berjalan',
    ],
    'You have no assets in your watchlist': [
        null,
        'Anda tidak memiliki aset pada daftar pantauan',
    ],
    Basic: [null, 'Dasar'],
    Digits: [null, 'Digit'],
    Advanced: [null, 'Lanjutan'],
    Higher: [null, 'Higher'],
    Lower: [null, 'Lower'],
    'Ends Outside': [null, 'Ends Outside'],
    'Ends Between': [null, 'Ends Between'],
    'Stays Between': [null, 'Stays Between'],
    'Goes Outside': [null, 'Goes Outside'],
    'Does Not Touch': [null, 'Does Not Touch'],
    'Credit / Debit': [null, 'Kredit / Debit'],
    'Last 25 Ticks': [null, '25 Tik Terakhir'],
    'Last 50 Trades': [null, '50 Tik Terakhir'],
    'Last 100 Trades': [null, '100 Trading Terakhir'],
    'Last 500 Trades': [null, '500 Trading Terakhir'],
    'Last 1000 Trades': [null, '1000 Trading Terakhir'],
    'Maximum Daily Turnover': [null, 'Maksimum Turnover Harian'],
    Commodities: [null, 'Komoditas'],
    'Major Pairs': [null, 'Pasangan Utama'],
    'Minor Pairs': [null, 'Pasangan Tambahan'],
    'Smart FX': [null, 'Smart FX'],
    'Volatility Indices': [null, 'Indeks Volatilitas'],
    Indices: [null, 'Indeks'],
    'OTC Stocks': [null, 'Saham OTC'],
    'Stated limits are subject to change without prior notice': [
        null,
        'Batas dapat berubah tanpa pemberitahuan terlebih dahulu',
    ],
    'Withdrawal Limits': [null, 'Batas Penarikan'],
    'Withdrawal limit': [null, 'Batas Penarikan'],
    'Already withdrawn': [null, 'Sudah ditarik'],
    'Current immediate maximum withdrawal': [
        null,
        'Jumlah maksimal penarikan saat ini',
    ],
    'Create Free Account': [null, 'Daftar Akun Gratis'],
    'Verification Code': [null, 'Kode Verifikasi'],
    'Confirm Password': [null, 'Konfirmasi Kata Sandi'],
    'Already have an account?': [null, 'Sudah memiliki akun?'],
    'Enter a valid verification code': [
        null,
        'Masukkan kode verifikasi yang berlaku',
    ],
    'Choose your country': [null, 'Pilih negara Anda'],
    'Password should have lower and uppercase letters and 6 characters or more': [
        null,
        'Kata sandi harus memiliki huruf kecil, huruf besar dan 6 karakter atau lebih',
    ],
    'Passwords do not match': [null, 'Kata sandi tidak cocok'],
    'Enter a valid email': [null, 'Masukkan email yang benar'],
    'Number should between 10 to 120': [null, 'Nomor harus antara 10-120'],
    'Enter your first and last name': [
        null,
        'Masukkan nama depan dan belakang Anda',
    ],
    'City must not be empty': [null, 'Kota tidak boleh kosong'],
    'Address must not be empty': [null, 'Alamat tidak boleh kosong'],
    'Enter a valid phone number': [null, 'Masukkan nomor telepon yang benar'],
    'Select a secret question': [null, 'Pilih pertanyaan rahasia'],
    'Secret answer must be at least 4 characters': [
        null,
        'Jawaban rahasia harus minimal 4 karakter',
    ],
    'You need to agree to our Terms and Conditions': [
        null,
        'Anda perlu menyetujui Syarat dan Ketentuan kami',
    ],
    'I agree to the': [null, 'Saya setuju dengan'],
    'terms and conditions': [null, 'syarat dan ketentuan'],
    'Search for assets': [null, 'Pencarian aset'],
    'Choose a Payment Agent': [null, 'Pilih Agen Pembayaran'],
    'Confirm New Password': [null, 'Konfirmasi Kata Sandi Baru'],
    'First Name': [null, 'Nama Depan'],
    'Last Name': [null, 'Nama Belakang'],
    'Address First Line': [null, 'Baris Pertama Alamat'],
    'Address Second Line': [null, 'Baris Kedua Alamat'],
    Phone: [null, 'Telepon'],
    'Answer To Secret Question': [null, 'Jawaban Untuk Pertanyaan Rahasia'],
    'Switch to': [null, 'Beralih ke'],
    'Single Trade': [null, 'Trading Tunggal'],
    'Multi Trade': [null, 'Multi Trading'],
    'Current Password': [null, 'Kata Sandi Saat Ini'],
    'New Password': [null, 'Kata Sandi Baru'],
    'Last 50 Ticks': [null, '50 Tik Terakhir'],
    'Last 100 Ticks': [null, '100 Tik Terakhir'],
    'Last 500 Ticks': [null, '500 Tik Terakhir'],
    'Last 1000 Ticks': [null, '1000 Tik Terakhir'],
    'Exit Full Screen': [null, 'Keluar Dari Layar Penuh'],
    'No digit trades for this asset': [null, ''],
    'Password changed successfully': [null, ''],
    'Duration is out of range': [null, ''],
    'Start date invalid, it needs to be five minutes or more in the future': [
        null,
        '',
    ],
    'Time format is wrong': [null, ''],
};
