export default {
    '': {
        'project-id-version': 'PACKAGE VERSION',
        'pot-creation-date': '',
        'po-revision-date': '2016-08-09 20:27+0000',
        'last-translator': 'Annalisa <ligiu@me.com>',
        'language-team': 'Italian <https://hosted.weblate.org/projects/binary-app/next-gen-app/it/>',
        language: 'it',
        'mime-version': '1.0',
        'content-type': 'text/plain; charset=UTF-8',
        'content-transfer-encoding': '8bit',
        'plural-forms': 'nplurals=2; plural=n != 1;',
        'x-generator': 'Weblate 2.8-dev',
    },
    All: [null, 'Tutto'],
    Property: [null, 'Proprietà'],
    Value: [null, 'Valore'],
    Balance: [null, 'Saldo'],
    Trade: [null, 'Trade'],
    Watchlist: [null, 'Watchlist'],
    'Open Positions': [null, 'Posizioni aperte'],
    'Profit Table': [null, 'Tabella dei profitti'],
    Statement: [null, 'Estratto'],
    Settings: [null, 'Impostazioni'],
    'Sign Out': [null, 'Esci'],
    View: [null, 'Mostra'],
    'Ref.': [null, 'Rif.'],
    Purchase: [null, 'Acquisto'],
    Indicative: [null, 'Indicativo'],
    'Purchase Date': [null, "Data d'acquisto"],
    'Purchase Price': [null, "Prezzo d'acquisto"],
    'Sale Date': [null, 'Data della vendita'],
    'Sale Price': [null, 'Prezzo di vendita'],
    'Profit/Loss': [null, 'Profitto/Perdita'],
    Total: [null, 'Totale'],
    Location: [null, 'Posizione'],
    Update: [null, 'Aggiorna'],
    Details: [null, 'Dettagli'],
    'Trading Limits': [null, 'Limiti del trading'],
    Item: [null, 'Voce'],
    'Limit ({currency})': [null, 'Limite ({currency})'],
    'Maximum number of open positions': [
        null,
        'Numero massimo di posizioni aperte',
    ],
    'Maximum account cash balance': [null, "Saldo massimo dell'account"],
    'Maximum daily turnover': [null, 'Turnover massimo giornaliero'],
    'Maximum aggregate payouts on open positions': [
        null,
        'Payout totali massimi su posizioni aperte',
    ],
    'Withdrawal limits': [null, 'Limiti per i prelievi'],
    'Your withdrawal limit is {limit} (or equivalent in other currency).': [
        null,
        'Il tuo limite di prelievo è di {limit} (o equivalente in altra valuta).',
    ],
    'You have already withdrawn the equivalent of EUR {drawn}.': [
        null,
        "Hai già prelevato l'equivalente di EUR {drawn}.",
    ],
    'An additional password can be used to restrict access to the cashier.': [
        null,
        "Può essere utilizzata una password aggiuntiva per limitare l'accesso alla cassa.",
    ],
    'Sign In': [null, 'Entra'],
    'Get your API token': [null, 'Ottieni il tuo token API'],
    'Create Account': [null, 'Crea un account'],
    Action: [null, 'Azione'],
    'Credit/Debit': [null, 'Credito/Debito'],
    'Purchase Time': [null, "Orario d'acquisto"],
    Back: [null, 'Precedente'],
    'Place Order': [null, 'Effettua un ordine'],
    '{asset} will {type} over next {duration}': [
        null,
        '{asset} sarà {type} per i prossimi {duration}',
    ],
    Price: [null, 'Prezzo'],
    Asset: [null, 'Asset'],
    Type: [null, 'Tipologia'],
    Ticks: [null, 'Tick'],
    Amount: [null, 'Importo'],
    'Trade Confirmation': [null, 'Conferma del trade'],
    'Entry spot': [null, "Punto d'ingresso"],
    'Exit spot': [null, 'Prezzo di uscita'],
    Next: [null, 'Successivo'],
    'Open Account': [null, 'Apri un account'],
    'Upgrade to Real Money Account': [
        null,
        'Passa a un account con soldi veri',
    ],
    'Date of birth': [null, 'Data di nascita'],
    'Home Address': [null, 'Indirizzo di residenza'],
    Security: [null, 'Sicurezza'],
    Spot: [null, 'Spot'],
    Change: [null, 'Cambio'],
    Chart: [null, 'Grafico'],
    'Purchase For': [null, 'Acquisto per'],
    Rise: [null, 'Aumento'],
    Stake: [null, 'Puntata'],
    Payout: [null, 'Payout'],
    Deposit: [null, 'Deposito'],
    Transactions: [null, 'Transazioni'],
    Opens: [null, 'Apre'],
    Closes: [null, 'Chiude'],
    Personal: [null, 'Personale'],
    General: [null, 'Generale'],
    'Trading Times': [null, 'Orari di trading'],
    'Asset Index': [null, 'Indice degli asset'],
    Today: [null, 'Oggi'],
    Yesterday: [null, 'Ieri'],
    Tomorrow: [null, 'Domani'],
    Takeout: [null, 'Takeout'],
    News: [null, 'Novità'],
    Resources: [null, 'Risorse'],
    'Last 7 Days': [null, 'Ultimi 7 giorni'],
    'Last 30 Days': [null, 'Ultimi 30 giorni'],
    'Daily Report': [null, 'Report giornaliero'],
    'Up/Down': [null, 'Up/Down'],
    'Touch/No Touch': [null, 'Touch/No Touch'],
    'Ends In/Out': [null, 'Ends In/Out'],
    'Stays In/Goes Out': [null, 'Stays in/Goes Out'],
    Settles: [null, 'Risolve'],
    Language: [null, 'Lingua'],
    'Color Theme': [null, 'Tema a colori'],
    Light: [null, 'Chiaro'],
    Dark: [null, 'Scuro'],
    Name: [null, 'Nome'],
    'Date Of Birth': [null, 'Data di nascita'],
    'Country Of Residence': [null, 'Paese di residenza'],
    Email: [null, 'Email'],
    'There are no transactions for selected period': [
        null,
        'Non ci sono transazioni per il periodo selezionato',
    ],
    Sell: [null, 'Vendi'],
    Buy: [null, 'Acquista'],
    'Digit Even': [null, 'Cifra pari'],
    Touches: [null, 'Touch'],
    'Digit Over': [null, 'Cifra superiore'],
    'Digit Match': [null, 'Cifra uguale'],
    'Digit Under': [null, 'Cifra inferiore'],
    'Digit Odd': [null, 'Cifra dispari'],
    'Digit Differs': [null, 'Cifra diversa'],
    'No Touch': [null, 'No Touch'],
    Fall: [null, 'Fall'],
    'Asian Down': [null, 'Asiatiche Down'],
    'Asian Up': [null, 'Asiatiche Up'],
    'Search For Assets': [null, 'Ricerca di asset'],
    'Start times': [null, 'Orari di inizio'],
    Durations: [null, 'Durate'],
    'Payout/Stake': [null, 'Payout/Puntata'],
    'Purchase for': [null, 'Acquista per'],
    payout: [null, 'payout'],
    stake: [null, 'puntata'],
    'Self Exclusion': [null, 'Auto esclusione'],
    'Cashier Lock': [null, 'Blocco della cassa'],
    'Change Password': [null, 'Modifica password'],
    Password: [null, 'Password'],
    'Tick Trade': [null, 'Tick Trade'],
    'Full Trade': [null, 'Full Trade'],
    Address: [null, 'Indirizzo'],
    'Town/City': [null, 'Città'],
    'State/Province': [null, 'Stato/Provincia'],
    Telephone: [null, 'Telefono'],
    'Postal Code / ZIP': [null, 'Codice postale/CAP'],
    'Cashier password': [null, 'Password della cassa'],
    'Re-enter your password': [null, 'Reinserisci la tua password'],
    'Current password': [null, 'Password attuale'],
    'New password': [null, 'Nuova password'],
    'Verify new password': [null, 'Verifica la nuova password'],
    'Daily turnover limit': [null, 'Limite di turnover giornaliero'],
    'Once this limit is reached, you may no longer deposit.': [
        null,
        'Una volta raggiunto questo limite, non potrai più depositare.',
    ],
    'Maximum aggregate contract purchases per day.': [
        null,
        "Contratti d'acquisto aggregati massimi giornalieri.",
    ],
    'Daily limit on losses': [null, 'Limite giornaliero sulle perdite'],
    'Maximum aggregate loss per day.': [
        null,
        'Perdita aggregata massima giornaliera.',
    ],
    '7-day turnover limit': [null, 'Limite di turnover su 7 giorni'],
    'Maximum aggregate contract purchases over a 7-day period.': [
        null,
        'Acquisti di contratti aggregati massimi in un periodo di 7 giorni.',
    ],
    '7-day limit on losses': [null, 'Limite di 7 giorni sulle perdite'],
    'Maximum aggregate loss over a 7-day period.': [
        null,
        'Perdita aggregata massima su un periodo di 7 giorni.',
    ],
    '30-day turnover limit': [null, 'Limite di turnover di 30 giorni'],
    'Maximum aggregate contract purchases over a 30-day period.': [
        null,
        'Acquisti massimi di contratti aggregati su un periodo di 30 giorni.',
    ],
    '30-day limit on losses': [null, 'Limite di 30 giorni sulle perdite'],
    'Maximum aggregate loss over a 30-day period.': [
        null,
        'Perdita aggregata massima su un periodo di 30 giorni.',
    ],
    'Session duration limit, in minutes': [
        null,
        'Limite di durata della sessione, in minuti',
    ],
    'You will be automatically logged out after such time.': [
        null,
        'Dopo tale orario, verrai automaticamente loggato.',
    ],
    'Exclude me from the website until': [
        null,
        'Escludimi dal sito internet fino',
    ],
    Limits: [null, 'Limiti'],
    'Please enter date in the format YYYY-MM-DD.': [
        null,
        'Si prega di inserire la data nel formato AAAA-MM-GG.',
    ],
    'New Trade': [null, 'Nuovo trade'],
    'Trade Type': [null, 'Tipologia di trade'],
    'Random 100 Index': [null, 'Indice Random 100'],
    Article: [null, 'Articolo'],
    'Start Later': [null, 'Inizia più tardi'],
    'Buy Price': [null, "Prezzo d'acquisto"],
    'Earning (%)': [null, 'Guadagno (%)'],
    Profit: [null, 'Profitto'],
    'Entry Price': [null, "Prezzo d'ingresso"],
    'Exit Price': [null, "Prezzo d'uscita"],
    'Indicative Price': [null, 'Prezzo indicativo'],
    'Potential Profit': [null, 'Profitto potenziale'],
    'Sell at Market': [null, 'Vendi sul mercato'],
    'Go back': [null, 'Torna indietro'],
    'You lost ': [null, 'Hai perso '],
    Close: [null, 'Chiuso'],
    Low: [null, 'Low'],
    High: [null, 'High'],
    Open: [null, 'Apre'],
    Date: [null, 'Data'],
    'Upcoming Events': [null, 'Prossimi eventi'],
    Win: [null, 'Vincita'],
    Loss: [null, 'Perdita'],
    'Full Screen': [null, 'Schermo intero'],
    'Start Now': [null, 'Inizia ora'],
    'Daily Prices': [null, 'Prezzi giornalieri'],
    Spreads: [null, 'Spread'],
    'Confirm new password': [null, 'Conferma la nuova password'],
    TICK: [null, 'TICK'],
    Minutes: [null, 'Minuti'],
    Seconds: [null, 'Secondi'],
    Hours: [null, 'Ore'],
    Days: [null, 'Giorni'],
    'N/A': [null, 'N/A'],
    Duration: [null, 'Durata'],
    'Start Time': [null, "Orario d'inizio"],
    Now: [null, 'Ora'],
    Later: [null, 'Dopo'],
    return: [null, 'rendimento'],
    Portfolio: [null, 'Portfolio'],
    Video: [null, 'Video'],
    'Digit Stats': [null, 'Statistiche per una cifra'],
    Favorites: [null, 'Preferiti'],
    'Open For Trading': [null, 'Aperto al trading'],
    Closed: [null, 'Chiuso'],
    'Contract ID': [null, 'ID del contratto'],
    'Reference ID': [null, 'ID di riferimento'],
    'Entry Spot': [null, "Prezzo d'ingresso"],
    'Entry Spot Time': [null, "Orario del prezzo d'ingresso"],
    'Potential Payout': [null, 'Payout potenziale'],
    'Exit Spot': [null, 'Prezzo di uscita'],
    'Exit Spot Time': [null, 'Orario del prezzo di uscita'],
    'Sell Price': [null, 'Prezzo di vendita'],
    'Sell Time': [null, 'Orario di vendita'],
    'Trade Again': [null, 'Negozia di nuovo'],
    Barrier: [null, 'Barriera'],
    'You Won': [null, 'Hai vinto'],
    'You Lost': [null, 'Hai perso'],
    'To change your name, date of birth, country of residence, or email, contact Customer Support.': [
        null,
        "Per modificare il tuo nome, data di nascita, paese di residenza o email, contatta l'Assistenza Clienti.",
    ],
    'Cashier is locked per your request. To unlock it, enter your password.': [
        null,
        'Come da tua richiesta, la cassa è bloccata. Per sbloccarla, inserisci la password.',
    ],
    'Unlock Cashier': [null, 'Sblocca la cassa'],
    'Time out until': [null, 'Tempo scaduto fino a'],
    'No transactions for the selected period': [
        null,
        'Non ci sono transazioni per il periodo selezionato',
    ],
    'You have no open contracts': [null, 'Non hai alcun contratto aperto'],
    'You have no assets in your watchlist': [null, "Non hai asset nell'elenco"],
    Basic: [null, 'Base'],
    Digits: [null, 'Cifre'],
    Advanced: [null, 'Avanzato'],
    Higher: [null, 'Superiore'],
    Lower: [null, 'Inferiore'],
    'Ends Outside': [null, 'Termina fuori'],
    'Ends Between': [null, 'Termina fra'],
    'Stays Between': [null, 'Rimane fra'],
    'Goes Outside': [null, 'Esce da'],
    'Does Not Touch': [null, 'Non tocca'],
    'Credit / Debit': [null, 'Credito / Debito'],
    'Last 25 Ticks': [null, 'Ultimi 25 tick'],
    'Last 50 Trades': [null, 'Ultimi 50 trade'],
    'Last 100 Trades': [null, 'Ultimi 100 trade'],
    'Last 500 Trades': [null, 'Ultimi 500 trade'],
    'Last 1000 Trades': [null, 'Ultimi 1000 trade'],
    'Maximum Daily Turnover': [null, 'Turnover massimo giornaliero'],
    Commodities: [null, 'Materie prime'],
    'Major Pairs': [null, 'Coppie principali'],
    'Minor Pairs': [null, 'Coppie minori'],
    'Smart FX': [null, 'Smart FX'],
    'Volatility Indices': [null, 'Indici di volatilità'],
    Indices: [null, 'Indici'],
    'OTC Stocks': [null, 'Azioni OTC'],
    'Stated limits are subject to change without prior notice': [
        null,
        'I limiti stabiliti possono essere modificati senza preavviso',
    ],
    'Withdrawal Limits': [null, 'Limiti per i prelievi'],
    'Withdrawal limit': [null, 'Limite per i prelievi'],
    'Already withdrawn': [null, 'Già prelevato'],
    'Current immediate maximum withdrawal': [
        null,
        'Attuale prelievo massimo immediato',
    ],
    'Create Free Account': [null, 'Crea un account gratis'],
    'Verification Code': [null, 'Codice di verifica'],
    'Confirm Password': [null, 'Conferma la password'],
    'Already have an account?': [null, 'Hai già un account?'],
    'Enter a valid verification code': [
        null,
        'Inserisci un codice di verifica valido',
    ],
    'Choose your country': [null, 'Scegli il tuo paese'],
    'Password should have lower and uppercase letters and 6 characters or more': [
        null,
        'La password deve contenere lettere minuscole e maiuscole e almeno 6 caratteri',
    ],
    'Passwords do not match': [null, 'Le password non corrispondono'],
    'Enter a valid email': [null, 'Inserisci un indirizzo email valido'],
    'Number should between 10 to 120': [
        null,
        'Il numero deve essere tra 10 e 120',
    ],
    'Enter your first and last name': [null, 'Inserisci il tuo nome e cognome'],
    'City must not be empty': [null, 'La città non deve essere vuota'],
    'Address must not be empty': [null, "L'indirizzo non deve essere vuoto"],
    'Enter a valid phone number': [
        null,
        'Inserisci un numero di telefono valido',
    ],
    'Select a secret question': [null, 'Seleziona una domanda segreta'],
    'Secret answer must be at least 4 characters': [
        null,
        'La risposta segreta deve contenere almeno 4 caratteri',
    ],
    'You need to agree to our Terms and Conditions': [
        null,
        'Devi accettare i nostri Termini e condizioni',
    ],
    'I agree to the': [null, 'Accetto i'],
    'terms and conditions': [null, 'termini e condizioni'],
    'Search for assets': [null, 'Ricerca di asset'],
    'Choose a Payment Agent': [null, 'Scegli un agente di pagamento'],
    'Confirm New Password': [null, 'Conferma la nuova password'],
    'First Name': [null, 'Nome'],
    'Last Name': [null, 'Cognome'],
    'Address First Line': [null, "Prima riga dell'indirizzo"],
    'Address Second Line': [null, "Seconda linea dell'indirizzo"],
    Phone: [null, 'Telefono'],
    'Answer To Secret Question': [null, 'Rispondi alla domanda segreta'],
    'Switch to': [null, 'Passa a'],
    'Single Trade': [null, 'Trade singolo'],
    'Multi Trade': [null, 'Più trade'],
    'Current Password': [null, 'Password attuale'],
    'New Password': [null, 'Password nuova'],
    'Last 50 Ticks': [null, 'Ultimi 50 tick'],
    'Last 100 Ticks': [null, 'Ultimi 100 tick'],
    'Last 500 Ticks': [null, 'Ultimi 500 tick'],
    'Last 1000 Ticks': [null, 'Ultimi 1000 tick'],
    'Exit Full Screen': [null, 'Esci dallo schermo intero'],
    'No digit trades for this asset': [null, ''],
    'Password changed successfully': [null, ''],
    'Duration is out of range': [null, ''],
    'Start date invalid, it needs to be five minutes or more in the future': [
        null,
        '',
    ],
    'Time format is wrong': [null, ''],
};
