export default {
    '': {
        'project-id-version': '1.0',
        'pot-creation-date': '',
        'po-revision-date': '2016-08-11 18:44+0000',
        'last-translator': 'Ewelina Bruździak <e.bruzdziak@gmail.com>',
        'language-team': 'Polish <https://hosted.weblate.org/projects/binary-app/next-gen-app/pl/>',
        language: 'pl',
        'mime-version': '1.0',
        'content-type': 'text/plain; charset=UTF-8',
        'content-transfer-encoding': '8bit',
        'plural-forms': 'nplurals=3; plural=n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;',
        'x-generator': 'Weblate 2.8-dev',
        'x-poedit-sourcecharset': 'UTF-8',
    },
    All: [null, 'Wszystko'],
    Property: [null, 'Właściwość'],
    Value: [null, 'Wartość'],
    Balance: [null, 'Saldo'],
    Trade: [null, 'Zakład'],
    Watchlist: [null, 'Obserwowane'],
    'Open Positions': [null, 'Otwarte pozycje'],
    'Profit Table': [null, 'Tabela zysków'],
    Statement: [null, 'Stan konta'],
    Settings: [null, 'Ustawienia'],
    'Sign Out': [null, 'Wyloguj'],
    View: [null, 'Widok'],
    'Ref.': [null, 'Ref.'],
    Purchase: [null, 'Kup'],
    Indicative: [null, 'Orientacyjna'],
    'Purchase Date': [null, 'Data zakupu'],
    'Purchase Price': [null, 'Cena zakupu'],
    'Sale Date': [null, 'Data sprzedaży'],
    'Sale Price': [null, 'Cena sprzedaży'],
    'Profit/Loss': [null, 'Zysk/Strata'],
    Total: [null, 'Całkowity'],
    Location: [null, 'Lokalizacja'],
    Update: [null, 'Aktualizuj'],
    Details: [null, 'Szczegóły'],
    'Trading Limits': [null, 'Limity handlowe'],
    Item: [null, 'Element'],
    'Limit ({currency})': [null, 'Limit ({currency})'],
    'Maximum number of open positions': [
        null,
        'Maksymalna liczba otwartych pozycji',
    ],
    'Maximum account cash balance': [
        null,
        'Maksymalne saldo gotówki na koncie',
    ],
    'Maximum daily turnover': [null, 'Maksymalny dzienny obrót'],
    'Maximum aggregate payouts on open positions': [
        null,
        'Maksymalne całkowite wypłaty dla pozycji otwartych',
    ],
    'Withdrawal limits': [null, 'Limity wypłat'],
    'Your withdrawal limit is {limit} (or equivalent in other currency).': [
        null,
        'Twój limit wypłat wynosi {limit} (lub jego ekwiwalent w innej walucie).',
    ],
    'You have already withdrawn the equivalent of EUR {drawn}.': [
        null,
        'Wypłacono już równowartość {drawn} EUR.',
    ],
    'An additional password can be used to restrict access to the cashier.': [
        null,
        'Możliwe jest użycie dodatkowego hasła, aby ograniczyć dostęp do sekcji Kasjer.',
    ],
    'Sign In': [null, 'Zaloguj'],
    'Get your API token': [null, 'Pobierz token API'],
    'Create Account': [null, 'Utwórz konto'],
    Action: [null, 'Czynność'],
    'Credit/Debit': [null, 'Winien/Ma'],
    'Purchase Time': [null, 'Godzina zakupu'],
    Back: [null, 'Poprzedni'],
    'Place Order': [null, 'Złóż zlecenie'],
    '{asset} will {type} over next {duration}': [
        null,
        '{asset} zanotuje {type} w ciągu {duration}',
    ],
    Price: [null, 'Cena'],
    Asset: [null, 'Aktywa'],
    Type: [null, 'Typ'],
    Ticks: [null, 'Najmniejsze zmiany ceny'],
    Amount: [null, 'Kwota'],
    'Trade Confirmation': [null, 'Potwierdzenie zawarcia zakładu'],
    'Entry spot': [null, 'Pozycja wejściowa'],
    'Exit spot': [null, 'Punkt wyjściowy'],
    Next: [null, 'Następny'],
    'Open Account': [null, 'Otwórz konto'],
    'Upgrade to Real Money Account': [
        null,
        'Zamień na konto z prawdziwymi pieniędzmi',
    ],
    'Date of birth': [null, 'Data urodzenia'],
    'Home Address': [null, 'Adres zamieszkania'],
    Security: [null, 'Bezpieczeństwo'],
    Spot: [null, 'Cena spot'],
    Change: [null, 'Zmiana'],
    Chart: [null, 'Wykres'],
    'Purchase For': [null, 'Kup za'],
    Rise: [null, 'Wzrost'],
    Stake: [null, 'Stawka'],
    Payout: [null, 'Wypłata'],
    Deposit: [null, 'Wpłata'],
    Transactions: [null, 'Transakcje'],
    Opens: [null, 'Otwarcie'],
    Closes: [null, 'Zamknięcie'],
    Personal: [null, 'Osobiste'],
    General: [null, 'Ogólne'],
    'Trading Times': [null, 'Godziny handlu'],
    'Asset Index': [null, 'Indeks aktywów'],
    Today: [null, 'Dzisiaj'],
    Yesterday: [null, 'Wczoraj'],
    Tomorrow: [null, 'Jutro'],
    Takeout: [null, 'Wypłata'],
    News: [null, 'Wiadomości'],
    Resources: [null, 'Zasoby'],
    'Last 7 Days': [null, 'Ostatnie 7 dni'],
    'Last 30 Days': [null, 'Ostatnie 30 dni'],
    'Daily Report': [null, 'Raport dzienny'],
    'Up/Down': [null, 'Góra/Dół'],
    'Touch/No Touch': [null, 'Osiągnie/Nie osiągnie'],
    'Ends In/Out': [null, 'Zakończy się w/poza'],
    'Stays In/Goes Out': [null, 'Pozostanie w/poza'],
    Settles: [null, 'Rozliczenia'],
    Language: [null, 'Język'],
    'Color Theme': [null, 'Motyw kolorystyczny'],
    Light: [null, 'Jasny'],
    Dark: [null, 'Ciemny'],
    Name: [null, 'Imię'],
    'Date Of Birth': [null, 'Data urodzenia'],
    'Country Of Residence': [null, 'Państwo zamieszkania'],
    Email: [null, 'E-mail'],
    'There are no transactions for selected period': [
        null,
        'Brak transakcji w wybranym okresie',
    ],
    Sell: [null, 'Sprzedaj'],
    Buy: [null, 'Kup'],
    'Digit Even': [null, 'Cyfra parzysta'],
    Touches: [null, 'Osiągnie'],
    'Digit Over': [null, 'Cyfra większa'],
    'Digit Match': [null, 'Cyfra zgadza się'],
    'Digit Under': [null, 'Cyfra mniejsza'],
    'Digit Odd': [null, 'Cyfra nieparzysta'],
    'Digit Differs': [null, 'Cyfra nie zgadza się'],
    'No Touch': [null, 'Nie osiągnie'],
    Fall: [null, 'Spadek'],
    'Asian Down': [null, 'Azjatycki – Spadek'],
    'Asian Up': [null, 'Azjatycki – Wzrost'],
    'Search For Assets': [null, 'Szukaj aktywów'],
    'Start times': [null, 'Czas rozpoczęcia'],
    Durations: [null, 'Czas trwania'],
    'Payout/Stake': [null, 'Wypłata/Stawka'],
    'Purchase for': [null, 'Kup za'],
    payout: [null, 'wypłata'],
    stake: [null, 'stawka'],
    'Self Exclusion': [null, 'Samodzielne wyłączenie'],
    'Cashier Lock': [null, 'Blokowanie sekcji Kasjer'],
    'Change Password': [null, 'Zmień hasło'],
    Password: [null, 'Hasło'],
    'Tick Trade': [null, 'Zakład oparty na najmniejszej zmianie ceny'],
    'Full Trade': [null, 'Pełny zakład'],
    Address: [null, 'Adres'],
    'Town/City': [null, 'Miasto'],
    'State/Province': [null, 'Region/Województwo'],
    Telephone: [null, 'Telefon'],
    'Postal Code / ZIP': [null, 'Kod pocztowy'],
    'Cashier password': [null, 'Hasło do sekcji Kasjer'],
    'Re-enter your password': [null, 'Powtórz hasło'],
    'Current password': [null, 'Obecne hasło'],
    'New password': [null, 'Nowe hasło'],
    'Verify new password': [null, 'Zweryfikuj nowe hasło'],
    'Daily turnover limit': [null, 'Maksymalny dzienny limit obrotów'],
    'Once this limit is reached, you may no longer deposit.': [
        null,
        'Po osiągnięciu tego limitu nie można dokonywać dalszych wpłat.',
    ],
    'Maximum aggregate contract purchases per day.': [
        null,
        'Maksymalne dzienne łączne zakupy kontraktów.',
    ],
    'Daily limit on losses': [null, 'Dzienny limit strat'],
    'Maximum aggregate loss per day.': [
        null,
        'Maksymalna łączna strata dzienna.',
    ],
    '7-day turnover limit': [null, '7-dniowy limit obrotów'],
    'Maximum aggregate contract purchases over a 7-day period.': [
        null,
        'Maksymalne łączne 7-dniowe zakupy kontraktów.',
    ],
    '7-day limit on losses': [null, '7-dniowy limit strat'],
    'Maximum aggregate loss over a 7-day period.': [
        null,
        'Maksymalna łączna strata w okresie 7-dniowym.',
    ],
    '30-day turnover limit': [null, '30-dniowy limit obrotów'],
    'Maximum aggregate contract purchases over a 30-day period.': [
        null,
        'Maksymalne łączne zakupy kontraktów w okresie 30 dni.',
    ],
    '30-day limit on losses': [null, '30-dniowy limit strat'],
    'Maximum aggregate loss over a 30-day period.': [
        null,
        'Maksymalna łączna strata w okresie 30-dni.',
    ],
    'Session duration limit, in minutes': [
        null,
        'Limit czasu sesji, w minutach',
    ],
    'You will be automatically logged out after such time.': [
        null,
        'Zostaniesz automatycznie wylogowany po tym czasie.',
    ],
    'Exclude me from the website until': [
        null,
        'Wyłącz mnie z portalu do dnia',
    ],
    Limits: [null, 'Limity'],
    'Please enter date in the format YYYY-MM-DD.': [
        null,
        'Wpisz datę w formacie RRRR-MM-DD.',
    ],
    'New Trade': [null, 'Nowy zakład'],
    'Trade Type': [null, 'Rodzaj zakładu'],
    'Random 100 Index': [null, 'Indeks losowy 100'],
    Article: [null, 'Artykuł'],
    'Start Later': [null, 'Rozpocznij później'],
    'Buy Price': [null, 'Cena zakupu'],
    'Earning (%)': [null, 'Dochód (%)'],
    Profit: [null, 'Zysk'],
    'Entry Price': [null, 'Cena wejściowa'],
    'Exit Price': [null, 'Cena wyjściowa'],
    'Indicative Price': [null, 'Cena orientacyjna'],
    'Potential Profit': [null, 'Potencjalny zysk'],
    'Sell at Market': [null, 'Sprzedaj na rynku'],
    'Go back': [null, 'Wróć'],
    'You lost ': [null, 'Poniesiono stratę '],
    Close: [null, 'Zamknij'],
    Low: [null, 'Niski'],
    High: [null, 'Wysoki'],
    Open: [null, 'Otwarte'],
    Date: [null, 'Data'],
    'Upcoming Events': [null, 'Nadchodzące wydarzenia'],
    Win: [null, 'Wygrana'],
    Loss: [null, 'Strata'],
    'Full Screen': [null, 'Pełny ekran'],
    'Start Now': [null, 'Rozpocznij teraz'],
    'Daily Prices': [null, 'Ceny dzienne'],
    Spreads: [null, 'Spready'],
    'Confirm new password': [null, 'Potwierdź nowe hasło'],
    TICK: [null, 'NAJMNIEJSZA ZMIANA CENY'],
    Minutes: [null, 'Minuty'],
    Seconds: [null, 'Sekundy'],
    Hours: [null, 'Godziny'],
    Days: [null, 'Dni'],
    'N/A': [null, 'Nie dotyczy'],
    Duration: [null, 'Czas trwania'],
    'Start Time': [null, 'Godzina rozpoczęcia'],
    Now: [null, 'Teraz'],
    Later: [null, 'Później'],
    return: [null, 'zwrot'],
    Portfolio: [null, 'Portfolio'],
    Video: [null, 'Nagranie'],
    'Digit Stats': [null, 'Statystyki cyfry'],
    Favorites: [null, 'Ulubione'],
    'Open For Trading': [null, 'Otwarte do handlowania'],
    Closed: [null, 'Zamknięte'],
    'Contract ID': [null, 'ID kontraktu'],
    'Reference ID': [null, 'ID referencyjne'],
    'Entry Spot': [null, 'Pozycja wejściowa'],
    'Entry Spot Time': [null, 'Czas pozycji wejściowej'],
    'Potential Payout': [null, 'Potencjalna wypłata'],
    'Exit Spot': [null, 'Pozycja wyjściowa'],
    'Exit Spot Time': [null, 'Czas pozycji wyjściowej'],
    'Sell Price': [null, 'Cena sprzedaży'],
    'Sell Time': [null, 'Czas sprzedaży'],
    'Trade Again': [null, 'Handluj ponownie'],
    Barrier: [null, 'Limit'],
    'You Won': [null, 'Wygrana'],
    'You Lost': [null, 'Przegrana'],
    'To change your name, date of birth, country of residence, or email, contact Customer Support.': [
        null,
        'Aby zmienić imię lub nazwisko, datę urodzenia, miejsce zamieszkania lub adres e-mail, skontaktuj się z działem obsługi klienta.',
    ],
    'Cashier is locked per your request. To unlock it, enter your password.': [
        null,
        'Sekcja Kasjer została zablokowana na Twoją prośbę. Aby ją odblokować, wpisz hasło.',
    ],
    'Unlock Cashier': [null, 'Odblokowywanie sekcji Kasjer'],
    'Time out until': [null, 'Przekroczono limit czasu do'],
    'No transactions for the selected period': [
        null,
        'Brak transakcji w wybranym okresie',
    ],
    'You have no open contracts': [
        null,
        'Nie masz żadnych otwartych kontraktów',
    ],
    'You have no assets in your watchlist': [
        null,
        'Nie masz żadnych aktywów na liście do obserwowania',
    ],
    Basic: [null, 'Podstawowe'],
    Digits: [null, 'Cyfry'],
    Advanced: [null, 'Zaawansowane'],
    Higher: [null, 'Wyższy'],
    Lower: [null, 'Niższy'],
    'Ends Outside': [null, 'Zakończy się poza'],
    'Ends Between': [null, 'Zakończy się pomiędzy'],
    'Stays Between': [null, 'Pozostanie pomiędzy'],
    'Goes Outside': [null, 'Przekroczy'],
    'Does Not Touch': [null, 'Nie osiągnie'],
    'Credit / Debit': [null, 'Winien/Ma'],
    'Last 25 Ticks': [null, 'Ostatnich 25 zmian cen'],
    'Last 50 Trades': [null, 'Ostatnie 50 zakładów'],
    'Last 100 Trades': [null, 'Ostatnie 100 zakładów'],
    'Last 500 Trades': [null, 'Ostatnie 500 zakładów'],
    'Last 1000 Trades': [null, 'Ostatnie 1000 zakładów'],
    'Maximum Daily Turnover': [null, 'Maksymalny dzienny obrót'],
    Commodities: [null, 'Towary'],
    'Major Pairs': [null, 'Główne pary'],
    'Minor Pairs': [null, 'Drugorzędne pary'],
    'Smart FX': [null, 'Inteligentne rynki forex'],
    'Volatility Indices': [null, 'Wskaźniki zmienności'],
    Indices: [null, 'Wskaźniki'],
    'OTC Stocks': [null, 'Akcje OTC'],
    'Stated limits are subject to change without prior notice': [
        null,
        'Określone limity mogą zostać zmienione bez wcześniejszego powiadomienia',
    ],
    'Withdrawal Limits': [null, 'Limity wypłat'],
    'Withdrawal limit': [null, 'Limit wypłat'],
    'Already withdrawn': [null, 'Już wypłacono'],
    'Current immediate maximum withdrawal': [
        null,
        'Obecna maksymalna natychmiastowa wypłata',
    ],
    'Create Free Account': [null, 'Utwórz darmowe konto'],
    'Verification Code': [null, 'Kod weryfikacyjny'],
    'Confirm Password': [null, 'Potwierdź hasło'],
    'Already have an account?': [null, 'Masz już konto?'],
    'Enter a valid verification code': [
        null,
        'Podaj prawidłowy kod weryfikacyjny',
    ],
    'Choose your country': [null, 'Wybierz swój kraj'],
    'Password should have lower and uppercase letters and 6 characters or more': [
        null,
        'Hasło powinno składać się z co najmniej 6 znaków i zawierać małe i wielkie litery',
    ],
    'Passwords do not match': [null, 'Hasła nie są zgodne'],
    'Enter a valid email': [null, 'Podaj prawidłowy adres e-mail'],
    'Number should between 10 to 120': [
        null,
        'Liczba powinna być z przedziału od 10 do 120',
    ],
    'Enter your first and last name': [null, 'Podaj swoje imię i nazwisko'],
    'City must not be empty': [null, 'Pole „miasto” nie może być puste'],
    'Address must not be empty': [null, 'Pole „adres” nie może być puste'],
    'Enter a valid phone number': [null, 'Podaj aktualny numer telefonu'],
    'Select a secret question': [null, 'Wybierz sekretne pytanie'],
    'Secret answer must be at least 4 characters': [
        null,
        'Odpowiedź na sekretne pytanie musi składać się z co najmniej 4 znaków',
    ],
    'You need to agree to our Terms and Conditions': [
        null,
        'Musisz zaakceptować nasz Regulamin',
    ],
    'I agree to the': [null, 'Akceptuję'],
    'terms and conditions': [null, 'regulamin'],
    'Search for assets': [null, 'Szukaj aktywów'],
    'Choose a Payment Agent': [null, 'Wybierz pośrednika płatności'],
    'Confirm New Password': [null, 'Potwierdź nowe hasło'],
    'First Name': [null, 'Imię'],
    'Last Name': [null, 'Nazwisko'],
    'Address First Line': [null, 'Adres - część pierwsza'],
    'Address Second Line': [null, 'Adres - część druga'],
    Phone: [null, 'Telefon'],
    'Answer To Secret Question': [null, 'Odpowiedź na sekretne pytanie'],
    'Switch to': [null, 'Zmień na'],
    'Single Trade': [null, 'Pojedynczy zakład'],
    'Multi Trade': [null, 'Multi zakład'],
    'Current Password': [null, 'Obecne hasło'],
    'New Password': [null, 'Nowe hasło'],
    'Last 50 Ticks': [null, 'Ostatnich 50 zmian cen'],
    'Last 100 Ticks': [null, 'Ostatnich 100 zmian cen'],
    'Last 500 Ticks': [null, 'Ostatnich 500 zmian cen'],
    'Last 1000 Ticks': [null, 'Ostatnich 1000 zmian cen'],
    'Exit Full Screen': [null, 'Zamknij pełny ekran'],
    'No digit trades for this asset': [null, ''],
    'Password changed successfully': [null, ''],
    'Duration is out of range': [null, ''],
    'Start date invalid, it needs to be five minutes or more in the future': [
        null,
        '',
    ],
    'Time format is wrong': [null, ''],
};
