export const SERVER_DATA_PORTFOLIO = 'SERVER_DATA_PORTFOLIO';
export const SERVER_DATA_PROPOSAL_OPEN_CONTRACT = 'SERVER_DATA_PROPOSAL_OPEN_CONTRACT';
export const DETAILS_FOR_CONTRACT = 'DETAILS_FOR_CONTRACT';
export const SERVER_DATA_PROPOSAL = 'SERVER_DATA_PROPOSAL';
export const UPDATE_TICK_TRADE_PARAMETERS = 'UPDATE_TICK_TRADE_PARAMETERS';
export const SERVER_DATA_BUY = 'SERVER_DATA_BUY';
export const DISCARD_PURCHASE_RECEIPT = 'SERVER_DISCARD_PURCHASE_RECEIPT';
export const UPDATE_OPEN_CONTRACT_FIELD = 'UPDATE_OPEN_CONTRACT_FIELD';

export const SERVER_DATA_AUTHORIZE = 'SERVER_DATA_AUTHORIZE';
export const SERVER_DATA_BALANCE = 'SERVER_DATA_BALANCE';
export const SERVER_DATA_ASSETS = 'SERVER_DATA_ASSETS';
export const SERVER_DATA_ACTIVE_SYMBOLS = 'SERVER_DATA_ACTIVE_SYMBOLS';
export const SERVER_DATA_TRADING_TIMES = 'SERVER_DATA_TRADING_TIMES';
export const SERVER_DATA_ASSET_INDEX = 'SERVER_DATA_ASSET_INDEX';
export const SERVER_DATA_STATEMENT = 'SERVER_DATA_STATEMENT';
export const SERVER_DATA_TRANSACTION = 'SERVER_DATA_TRANSACTION';

export const SERVER_DATA_TICK_STREAM = 'SERVER_DATA_TICK_STREAM';
export const SERVER_DATA_TICK_HISTORY = 'SERVER_DATA_TICK_HISTORY';
export const SERVER_DATA_CANDLES = 'SERVER_DATA_CANDLES';

export const UPDATE_ASSET_PICKER_SEARCH_QUERY = 'UPDATE_ASSET_PICKER_SEARCH_QUERY';
export const UPDATE_ASSET_PICKER_MARKETS = 'UPDATE_ASSET_PICKER_MARKETS';
export const UPDATE_ASSET_PICKER_SUBMARKET = 'UPDATE_ASSET_PICKER_SUBMARKET';
export const UPDATE_ASSET_PICKER_FILTER = 'UPDATE_ASSET_PICKER_FILTER';

export const UPDATE_TRADING_TIMES_FILTER = 'UPDATE_TRADING_TIMES_FILTER';
export const UPDATE_TRADING_TIMES_DATE = 'UPDATE_TRADING_TIMES_DATE';
export const UPDATE_ASSET_INDEX_FILTER = 'UPDATE_ASSET_INDEX_FILTER';
export const UPDATE_TRANSACTIONS_FILTER = 'UPDATE_TRANSACTIONS_FILTER';
export const SERVER_DATA_PAYOUT_CURRENCIES = 'SERVER_DATA_PAYOUT_CURRENCIES';
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const CHANGE_SELECTED_ASSET = 'CHANGE_SELECTED_ASSET';
export const CHANGE_ACTIVE_TRADE = 'CHANGE_ACTIVE_TRADE';
export const WORKSPACE_FAVOR_ASSET = 'WORKSPACE_FAVOR_ASSET';
export const WORKSPACE_UNFAVOR_ASSET = 'WORKSPACE_UNFAVOR_ASSET';
export const CLEAR_TRADE_TICKS = 'CLEAR_TRADE_TICKS';
export const UPDATE_WORKSPACE_FIELD = 'UPDATE_WORKSPACE_FIELD';
export const CHANGE_ACTIVE_LAYOUT = 'CHANGE_ACTIVE_LAYOUT';
export const CHANGE_ACTIVE_WORKSPACE_TAB = 'CHANGE_ACTIVE_WORKSPACE_TAB';
export const CHANGE_WORKSPACE_PANEL_SIZE = 'CHANGE_WORKSPACE_PANEL_SIZE';
export const CHANGE_TRADE_MODE = 'CHANGE_TRADE_MODE';
export const TOGGLE_TRADE_MODE = 'TOGGLE_TRADE_MODE';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_FIELD_UPDATE = 'SIGNIN_FIELD_UPDATE';

export const CHANGE_SETTINGS_ACTIVE_TAB = 'CHANGE_SETTINGS_ACTIVE_TAB';
export const SERVER_DATA_ACCOUNT_LIMITS = 'SERVER_DATA_ACCOUNT_LIMITS';
export const SERVER_DATA_ACCOUNT_SELF_EXCLUSION = 'SERVER_DATA_ACCOUNT_SELF_EXCLUSION';
export const SERVER_DATA_CHANGE_PASSWORD = 'SERVER_DATA_CHANGE_PASSWORD';
export const SERVER_DATA_CASHIER_LOCK = 'SERVER_DATA_CASHIER_LOCK';
export const SERVER_DATA_ACCOUNT_SETTINGS = 'SERVER_DATA_ACCOUNT_SETTINGS';
export const UPDATE_SETTINGS_FIELD = 'UPDATE_SETTINGS_FIELD';

export const UPDATE_NEWS_LIST = 'UPDATE_NEWS_LIST';

export const UPDATE_VIDEO_LIST = 'UPDATE_VIDEO_LIST';

export const WATCHLIST_TOGGLE_ASSET = 'WATCHLIST_TOGGLE_ASSET';

export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_NOW = 'UPDATE_NOW';

export const SERVER_DATA_PAYMENT_AGENTS = 'SERVER_DATA_PAYMENT_AGENTS';
export const UPDATE_PAYMENT_AGENT_FIELD = 'UPDATE_PAYMENT_AGENT_FIELD';
export const CREATE_ACCOUNT_FIELD_UPDATE = 'CREATE_ACCOUNT_FIELD_UPDATE';
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR';
export const CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START';

export const UPGRADE_FIELD_UPDATE = 'UPGRADE_FIELD_UPDATE';
export const UPGRADE_DOB_UPDATE = 'UPGRADE_DOB_UPDATE';
export const UPGRADE_FIELD_CLEAR = 'UPGRADE_FIELD_CLEAR';

export const SERVER_DATA_STATES = 'SERVER_DATA_STATES';

export const UPDATE_SYMBOL_FEED_LICENSE = 'UPDATE_SYMBOL_FEED_LICENSE';
export const UPDATE_TRADING_OPTIONS = 'UPDATE_TRADING_OPTIONS';
export const UPDATE_QUICK_TRADE_PARAMS = 'UPDATE_QUICK_TRADE_PARAMS';
export const SET_QUICK_TRADE_FIELD = 'SET_QUICK_TRADE_FIELD';

export const UPDATE_BOOT = 'UPDATE_BOOT';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const UPDATE_TRADE_PARAMS = 'UPDATE_TRADE_PARAMS';
export const UPDATE_MULTIPLE_TRADE_PARAMS = 'UPDATE_MULTIPLE_TRADE_PARAMS';

export const CREATE_TRADE = 'CREATE_TRADE';
export const REMOVE_TRADE = 'REMOVE_TRADE';
export const RESET_TRADES = 'RESET_TRADES';

export const REMOVE_PERSONAL_DATA = 'REMOVE_PERSONAL_DATA';

export const SERVER_DATA_TIME = 'SERVER_DATA_TIME';
