export default [{
    value: 'DE',
    text: 'Deutsch',
}, {
    value: 'EN',
    text: 'English',
}, {
    value: 'ES',
    text: 'Español',
}, {
    value: 'FR',
    text: 'Français',
}, {
    value: 'ID',
    text: 'Indonesia',
}, {
    value: 'IT',
    text: 'Italiano',
}, {
    value: 'JA',
    text: '日本語',
}, {
    value: 'PL',
    text: 'Polish',
}, {
    value: 'PT',
    text: 'Português',
}, {
    value: 'RU',
    text: 'Русский',
}, {
    value: 'TH',
    text: 'Thai',
}, {
    value: 'VI',
    text: 'Tiếng Việt',
}, {
    value: 'ZH_CN',
    text: '简体中文',
}, {
    value: 'ZH_TW',
    text: '繁體中文',
}];
